/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyFormationRouteImport } from './routes/company-formation'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingCertRouteImport } from './routes/training.$cert'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderThankYouRouteImport } from './routes/order.thank-you'
import { Route as OrderSlugRouteImport } from './routes/order.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyFormationRoute = CompanyFormationRouteImport.update({
  id: '/company-formation',
  path: '/company-formation',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCertRoute = TrainingCertRouteImport.update({
  id: '/$cert',
  path: '/$cert',
  getParentRoute: () => TrainingRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderThankYouRoute = OrderThankYouRouteImport.update({
  id: '/order/thank-you',
  path: '/order/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSlugRoute = OrderSlugRouteImport.update({
  id: '/order/$slug',
  path: '/order/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates': typeof CandidatesRoute
  '/company-formation': typeof CompanyFormationRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/guide': typeof GuideRoute
  '/industries': typeof IndustriesRoute
  '/recruiters': typeof RecruitersRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/training': typeof TrainingRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/order/$slug': typeof OrderSlugRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/product/$slug': typeof ProductSlugRoute
  '/training/$cert': typeof TrainingCertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates': typeof CandidatesRoute
  '/company-formation': typeof CompanyFormationRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/guide': typeof GuideRoute
  '/industries': typeof IndustriesRoute
  '/recruiters': typeof RecruitersRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/training': typeof TrainingRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/order/$slug': typeof OrderSlugRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/product/$slug': typeof ProductSlugRoute
  '/training/$cert': typeof TrainingCertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates': typeof CandidatesRoute
  '/company-formation': typeof CompanyFormationRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/guide': typeof GuideRoute
  '/industries': typeof IndustriesRoute
  '/recruiters': typeof RecruitersRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/training': typeof TrainingRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/order/$slug': typeof OrderSlugRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/product/$slug': typeof ProductSlugRoute
  '/training/$cert': typeof TrainingCertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/candidates'
    | '/company-formation'
    | '/contact'
    | '/delivery'
    | '/guide'
    | '/industries'
    | '/recruiters'
    | '/resources'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/start'
    | '/training'
    | '/api/contact'
    | '/order/$slug'
    | '/order/thank-you'
    | '/product/$slug'
    | '/training/$cert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/candidates'
    | '/company-formation'
    | '/contact'
    | '/delivery'
    | '/guide'
    | '/industries'
    | '/recruiters'
    | '/resources'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/start'
    | '/training'
    | '/api/contact'
    | '/order/$slug'
    | '/order/thank-you'
    | '/product/$slug'
    | '/training/$cert'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/candidates'
    | '/company-formation'
    | '/contact'
    | '/delivery'
    | '/guide'
    | '/industries'
    | '/recruiters'
    | '/resources'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/start'
    | '/training'
    | '/api/contact'
    | '/order/$slug'
    | '/order/thank-you'
    | '/product/$slug'
    | '/training/$cert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CandidatesRoute: typeof CandidatesRoute
  CompanyFormationRoute: typeof CompanyFormationRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  GuideRoute: typeof GuideRoute
  IndustriesRoute: typeof IndustriesRoute
  RecruitersRoute: typeof RecruitersRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  TrainingRoute: typeof TrainingRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  OrderSlugRoute: typeof OrderSlugRoute
  OrderThankYouRoute: typeof OrderThankYouRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-formation': {
      id: '/company-formation'
      path: '/company-formation'
      fullPath: '/company-formation'
      preLoaderRoute: typeof CompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$cert': {
      id: '/training/$cert'
      path: '/$cert'
      fullPath: '/training/$cert'
      preLoaderRoute: typeof TrainingCertRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/thank-you': {
      id: '/order/thank-you'
      path: '/order/thank-you'
      fullPath: '/order/thank-you'
      preLoaderRoute: typeof OrderThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$slug': {
      id: '/order/$slug'
      path: '/order/$slug'
      fullPath: '/order/$slug'
      preLoaderRoute: typeof OrderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrainingRouteChildren {
  TrainingCertRoute: typeof TrainingCertRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingCertRoute: TrainingCertRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CandidatesRoute: CandidatesRoute,
  CompanyFormationRoute: CompanyFormationRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  GuideRoute: GuideRoute,
  IndustriesRoute: IndustriesRoute,
  RecruitersRoute: RecruitersRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  TrainingRoute: TrainingRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  OrderSlugRoute: OrderSlugRoute,
  OrderThankYouRoute: OrderThankYouRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
